### ISSUE TITLE
Binutils not able to build (FW25 and FW26)

### ISSUE THREAD

**Issue by sjoerdboerhout** [WAGO/pfc-firmware-sdk-G2#13]
I'm trying to build some extra packages to deploy on the plc's. 

The package binutils is not able to build because the file binutils-2.38.20220708.tar.bz2 can't be retrieved. Its trying to download from multiple sources, but all are returning a 404 error. 

https://ftp.gnu.org/gnu/binutils/binutils-2.38.tar.bz2  does exists, but the requested 'https://ftp.gnu.org/gnu/binutils/binutils-2.38.20220708.tar.bz2' is not listed.

> --------------------------------------
> target: binutils-2.38.20220708.tar.bz2
> --------------------------------------
> 
> --2023-12-20 08:47:03--  https://ftp.gnu.org/gnu/binutils/binutils-2.38.20220708.tar.bz2
> Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b
> Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2023-12-20 08:47:03 ERROR 404: Not Found.
> 
> --2023-12-20 08:47:03--  http://ftp.uni-kl.de/pub/gnu/binutils/binutils-2.38.20220708.tar.bz2
> Resolving ftp.uni-kl.de (ftp.uni-kl.de)... 131.246.123.4, 2001:638:208:ef1b:0:ff:fe00:4
> Connecting to ftp.uni-kl.de (ftp.uni-kl.de)|131.246.123.4|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2023-12-20 08:47:03 ERROR 404: Not Found.
> 
> --2023-12-20 08:47:03--  https://www.pengutronix.de/software/ptxdist/temporary-src/binutils-2.38.20220708.tar.bz2
> Resolving www.pengutronix.de (www.pengutronix.de)... 95.216.103.100, 2a01:4f9:2a:2c17:5054:ff:fe65:8c93
> Connecting to www.pengutronix.de (www.pengutronix.de)|95.216.103.100|:443... connected.
> HTTP request sent, awaiting response... 307 Temporary Redirect
> Location: https://public.pengutronix.de/mirror/software/ptxdist/temporary-src/binutils-2.38.20220708.tar.bz2 [following]
> --2023-12-20 08:47:04--  https://public.pengutronix.de/mirror/software/ptxdist/temporary-src/binutils-2.38.20220708.tar.bz2
> Resolving public.pengutronix.de (public.pengutronix.de)... 95.216.103.100, 2a01:4f9:2a:2c17:5054:ff:fe65:8c93
> Connecting to public.pengutronix.de (public.pengutronix.de)|95.216.103.100|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2023-12-20 08:47:04 ERROR 404: Not Found.
> 
> Could not download package
> URL: https://ftp.gnu.org/gnu/binutils/binutils-2.38.20220708.tar.bz2 http://ftp.uni-kl.de/pub/gnu/binutils/binutils-2.38.20220708.tar.bz2
> 
> make: *** [/usr/local/lib/ptxdist-2020.08.0/rules/post/ptxd_make_world_get.make:16: /home/user/ptxproj/src/binutils-2.38.20220708.tar.bz2] Error 1
> 
> user@ad5450bcb610:~/ptxproj$ 

This was on revision:
a9bc94f (HEAD, tag: FW26-04.04.03, origin/main, origin/HEAD) Update 04.04.03-FW26

**Comment by falk-werner** [comment]
Hello @sjoerdboerhout,

Sorry for the late reply due to vacation. Please extract the following archive in the root directory of the SDK to enable binutils:  
[binutils_2.38_rules.zip](https://github.com/WAGO/pfc-firmware-sdk-G2/files/13859929/binutils_2.38_rules.zip)

The archive provides a PTXdist rule file for a fixed version of binutils (2.38), which fits for FW25 and FW26. The default rule file provided by PTXdists asks the toolchain for the specific version. Unfortunately our toolchain responds the exact version including the minor version number, which is correct for some use cases but not for binutils.

Please note that the binutils package is not part of our firmware image and will therefore not be maintained by WAGO. Since the version of binutils is bound to the toolchain version, it should be checked with each toolchain update. There is also a good chance that it might be fixed with the next toolchain update, just note that it will not be checked by WAGO.
